### ISSUE TITLE
VexFlow.com is broken. :-}

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1354]
It looks like the VexFlow 4 release broke the JSFiddle example on https://vexflow.com/  

This is because in version 4, we have changed the location of the library files to `vexflow/build/cjs/*` instead of `vexflow/releases/*`.

The JSFiddle includes: `https://npmcdn.com/vexflow/releases/vexflow-debug.js`  but that URL is actually redirected to the most recent NPM version. The URL is rewritten to: `https://npmcdn.com/vexflow@4.0.1/releases/vexflow-debug.js`

Unfortunately that URL doesn't exist, since we removed the vexflow/releases/ folder.

This means that any deployment that directly referenced the CDN URL above is now also broken. If the JSFiddle had included the version number 3.0.9 in the URL, it would still work fine: https://npmcdn.com/vexflow@3.0.9/releases/vexflow-debug.js

Even if we had kept the CJS files in the same location, it is possible that VexFlow 4 would have broken the old deployments, due to breaking changes.

## Possible Solution
I can augment our release script to add a `releases/` folder that restores version 3.0.9. I could make it so that these files are added *just before* pushing to NPM, so that our repository doesn't include unnecessary version 3.0.9 files.

Going forward, I think our README, tutorials, and JSFiddles should pin exact revision numbers. 

Instead of using URLs like:
```
https://unpkg.com/vexflow/build/cjs/vexflow.js
```

We should instead use URLs like:
```
https://unpkg.com/vexflow@4.0.1/build/cjs/vexflow.js
```

Many people copy and paste from example code, so if we omit the version number, that means their website will always get the newest version of vexflow (unpkg and jsdelivr CDNs redirect the version-less URLs to the most recent NPM version). This means that a future update could potentially break existing deployments.

Ideally, we should strive for backwards compatibility.... but it seems safer to just recommend that developers include the version number in the CDN URLs they use.

@0xfe Should I go ahead and restore the vexflow/releases/ folder with version 3.0.9, to support these old deployments?

**Comment by ronyeh** [comment]
On a Google search for "jsfiddle vexflow" we see that 6 out of 10 of the examples on the first page of results are broken:

```
4 JSFiddle examples use: https://npmcdn.com/vexflow/releases/vexflow-debug.js
2 JSFiddle examples use: https://rawgit.com/0xfe/vexflow/master/releases/vexflow-debug.js
```

The remaining 4 that still work point to old versions hosted on vexflow.com:
```
http://www.vexflow.com/support/vexflow-debug.js
http://www.vexflow.com/support/vexflow-min.js
http://www.vexflow.com/support/vexflow-min.js
http://vexflow.com/support/vexflow-min.js
```

**Comment by ronyeh** [comment]
@0xfe @rvilarl If I reintroduce the `releases` folder (just on NPM and nowhere else), should I put version 3.0.9 in there? Or should I put VexFlow 4 in there?

I feel like VexFlow 4 should be backwards compatible with most of the JSFiddle examples out in the wild, since those examples are all pretty simple.

However, putting 3.0.9 in there would probably result in fewer pages being broken.

What do you think should go in vexflow/releases/?
* VexFlow 4?
* 3.0.9?

**Comment by 0xfe** [comment]
I'd rather fix the examples in the website now to support our new model,
than try to be backward compatible for the website.

If you can provide new jsfiddle links, I'll go and change everything. (BTW,
this probably also affects the tutorials on the wiki.)

**Comment by 0xfe** [comment]
Re: vexflow-debug, which is referenced everywhere, maybe let's keep that in
releases (maybe 3.0.9), throw a huge console warning that it's going away,
and add a comment header too.) So we'll support that path for a bit, and
the delete it.

**Comment by ronyeh** [comment]
OK I thought about it some more. 

I believe that 4.0.1 is backwards compatible with most of the basic examples on JSFiddle. We only broke things that we thought were worth breaking. 

So I think I will add a releases/ folder that includes the 4.0.1 CJS version of vexflow-debug.js. This file won't be checked into the repo, but it will be pushed to NPM as part of the release script. I could add a console.log and comment to this file, letting any devs know that they should use a different URL. Eventually in 4.x or 5.0, we will no longer include this releases folder. This seems like an okay way to "deprecate" the old URL. 

I'll check over the wiki and tutorials to see which JSFiddles need to be updated. 

I'll also update the VexFlow.com JSFiddle and send you the new embed code to stick in the homepage.

**Comment by ronyeh** [comment]
@0xfe you can make these two updates to vexflow.com


# vexflow.com change 1
OLD:
```
<script async src="//jsfiddle.net/cr6vxo4k/embed/result,js/"></script>
```

NEW:
```
<script async src="//jsfiddle.net/pgmye7xo/embed/result,js"></script>
```

I fixed a typo and modernized the JS, and updated the VexFlow library URL. The old URL was: https://npmcdn.com/vexflow/releases/vexflow-debug.js  The URL has been updated to: https://unpkg.com/vexflow@4.0.1/build/cjs/vexflow-debug.js

# vexflow.com change 2

OLD:
```
<!-- VexFlow Compiled Source -->
<script src="https://unpkg.com/vexflow/releases/vexflow-debug.js"></script>
```

NEW:
```
<!-- VexFlow Compiled Source -->
<script src="https://unpkg.com/vexflow@3.0.9/releases/vexflow-debug.js"></script>
```

We pin the dependency to version 3.0.9 for now, because vexflow.com's compiled JS file (`index.6e3526b4920ed396a67c.js`) does not work with 4.0.1 due to the `addModifier()` parameter order.

**Comment by 0xfe** [comment]
ack

**Comment by 0xfe** [comment]
This is fixed. (Hand patched because all the dependencies are now stale, thanks to the rapidly evolving JS ecosystem.)

**Comment by stephaneeybert** [comment]
In an Angular strictly typed environment, I was using the `3.0.9` release with the types `@types/vexflow` release `1.2.37`.

Now after upgrading to the `4.0.1` release I get the following error in the browser:
`TypeError: staveNote.addAccidental is not a function`

I did not upgrade the `@types/vexflow` dependency.
I see the npm registry is still offering the `1.2.37` [release](https://www.npmjs.com/package/@types/vexflow).

I have no complaint from the Angular compiler. It's a runtime error.

**Comment by ronyeh** [comment]
Hello! Can you open a new issue so we can have a discussion on breaking changes in the new issue? It will help others who are upgrading from 3.0.9 to 4.0.1. 

addAccidental() was removed while we were debugging circular dependencies. Now, we call addModifier() directly. 

https://github.com/0xfe/vexflow/wiki/Changelog-ver-4.0#stavenote-removed-addaccidental-addarticulation-addannotation-adddot

We don't manage the types npm package. Instead, our project is in typescript and the type definitions are included as part of the 4.0.1 release. 

We can probably work with you to figure out how to get this integrated into Angular.

**Comment by ronyeh** [comment]
> I did not upgrade the `@types/vexflow` dependency.
> I see the npm registry is still offering the `1.2.37` [release](https://www.npmjs.com/package/@types/vexflow).

https://www.npmjs.com/package/@types/vexflow

The above types package is not managed by our team. It looks like external developers, including those from OSMD, contributed those types, since version 3.0.9 was written in pure JS and had no d.ts files. 

4.0.1 is in native typescript. What happens if you uninstall your @types/VexFlow.... will your compiler find the right .d.ts files under the 4.0.1 folder? You should be able to inspect node_modules/vexflow/ yourself and see the type definition files.

**Comment by stephaneeybert** [comment]
I created the new [issue](https://github.com/0xfe/vexflow/issues/1371).

**Comment by sschmidTU** [comment]
@stephaneeybert @types/vexflow only applies until vexflow 3.0.9. For vexflow 4, you can use vexflow's own types now, since it's in typescript now.
